### ISSUE TITLE
[Request] Decrease PSVITA volume further

### ISSUE THREAD

**Issue by Liquid-S** [cuevavirus/jav#2]
Hi, I'd like to make a feature request, but instead of a "feature" request per se, it's probably more of a "new plugin request", since I'm not exactly sure which would be the accurate category for it.

Anyway, I was wondering if it's possible to decrease the PSVITA sound volume below its standard limit. Using headphones at night is painful for me, since even at it's lowest the volume, the sound is too loud. Do you think it's possible to modify the PSVITA's volume limit?

Thanks for "JAV", it's a bless!

**Comment by cuevavirus** [comment]
Use [Monaural](https://github.com/cuevavirus/monaural) with mono audio disabled and left and right balance both lowered until the volume is sufficiently low.

**Comment by Liquid-S** [comment]
Thanks, that's what I was searching for! You’re awesome!
