### ISSUE TITLE
Not working on 3.65 testkit fw

### ISSUE THREAD

**Issue by khaotik666** [cuevavirus/jav#3]
Just recently bumped myself to 3.65 testkit firmware and noticed when it was loading back in that the volume bar didn't load up while setting back up. Went and grabbed my headphones to double check and still nothing. Moved it to the top of the main* section of the config.txt and still no luck.

on another note, thank you so much for adding the support to quick_volume and quick_power!

**Comment by cuevavirus** [comment]
I will add support for 3.65 testkit soon.

**Comment by cuevavirus** [comment]
Firmware support added in bccd79012498ecc30547d5dcbf2fb5cdef87ab0b and in release version 2.1.0.
