### ISSUE TITLE
2.0.0 Crash after warning menu [3.65]

### ISSUE THREAD

**Issue by Ayukito** [cuevavirus/jav#4]
I was messing around with load orders for this and just can't get 2.0.0 to work. It seems to work just fine with 1.1.0 though.

Plugins I use: (in case there's incompatibility?)
ioplus.skprx
lolicon.skprx
nolockscren.suprx
nonpdrm.skprx
adrenaline_kernel.skprx
NoPowerLimits.skprx
pngshot.suprx
reF00D.skprx
repatch.skprx
shellbat.suprx
storagemgr.skprx
udcd_uvc.skprx
vitabright.skprx
vitagrafix.suprx

and the [config](https://gist.github.com/Ayukito/ebf95d4fdef459c97272ea309231f5cb)

If there's any kind of logs I can provide, let me know.

**Comment by cuevavirus** [comment]
Can you please try this build and upload the log from `ux0:jav.txt`?

[jav.zip](https://github.com/cuevavirus/jav/files/4084933/jav.zip)

**Comment by Ayukito** [comment]
> Can you please try this build and upload the log from `ux0:jav.txt`?
> 
> [jav.zip](https://github.com/cuevavirus/jav/files/4084933/jav.zip)

I've narrowed it down to a plugin conflict with [udcd_uvc](https://github.com/xerpi/vita-udcd-uvc)

[Log with udcd_uvc](https://gist.github.com/Ayukito/c29c27f3adeb367151b34bd16e3833c9)

[Log without udcd_uvc (WORKS)](https://gist.github.com/Ayukito/cb571bc799d0c5f0c8037444bdf63401)

**Comment by cuevavirus** [comment]
Thank you. I will further investigate the conflict with udcd_uvc.

**Comment by cuevavirus** [comment]
Initially I was able to produce a crash with udcd_uvc and quick volume, but not with jav. Eventually after fiddling with my config and plugins for a while I was unable to produce any kind of crash.

So it might be a timing related problem (race condition) with jav or even a different plugin that is difficult to reproduce. I will keep udcd_uvc to see if I can reproduce it again but for now here's what you can do

1. Use version 1.1.0 if you don't need bluetooth features
2. If you want to you can disable everything except for udcd_uvc and jav and enable other stuff one by one until something causes a crash.

**Comment by Ayukito** [comment]
In the end it does seem to be a race condition, as I’ve encountered it with other plugins while singling out plugins one by one. The combination of jav, udcd_uvc, and various other plugins, such as nolockscreen, cause this. I’ll close this for now, because it doesn’t seem to be an issue on your end.
