### ISSUE TITLE
[Request] Music Playback stops when headphone is disconnected.

### ISSUE THREAD

**Issue by dkrmdi** [cuevavirus/jav#6]
Hi 

I'd like to know if you can make the music app pause when headphone is disconnected.

Also, would it be possible to control the music app with buttons while the screen is off?

Like go to next track or previous track using L R buttons. Stop and resume playback using o/x button. Fastforward using the d-pad all while the screen is off.

Is there any place where I can easily contact you or other PSV developers? I feel I should stop requesting in the issue section.

Thank you.

**Comment by cuevavirus** [comment]
Please join our discord server and make requests there https://discordapp.com/invite/2ccAkg3

I'll take note of these music app features you want but generally system applications are difficult to work with.

**Comment by dkrmdi** [comment]
I have joined the discord channel. Thank you. I'll close this case.
